name = "speakez"
main = "worker/index.js"
compatibility_date = "2025-01-01"

[vars]
DOMAIN = "speakez.brine.dev"
CONTACT = "ack@brine.dev"
OWNER = "XCIrv0pgfgF3DjBBNuO0dQkIWFbZyqHDZBWVjMHKhC8"  # single pubkey; the sovereign — promotes/demotes admins

[assets]
directory = "assets"
not_found_handling = "single-page-application"
binding = "ASSETS"

[[kv_namespaces]]
binding = "KV"
id = "fad796d3dddd40aa9ab5e1f4193b3fd6"

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]

[[r2_buckets]]
binding = "BACKUP"
bucket_name = "speakez-backup"

[triggers]
crons = ["*/5 * * * *"]
